import type { Metadata } from "next";
import localFont from "next/font/local";
import CookieConsent from "@/components/cookie-consent";
import SmoothScroll from "@/components/smoothscroll";
import "./globals.scss";

const geistSans = localFont({
  src: "../../public/font/Geist/static/Geist-Regular.woff2",
  variable: "--font-geist-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <CookieConsent />
        <SmoothScroll />
      </body>
    </html>
  );
}
